[tool.poetry]
name = "reinforcement-learning"
version = "0.1.0"
description = ""
authors = ["Gavin Strunk <gavin.strunk@ssci.com>"]
readme = "README.md"
packages = [{include = "reinforcement_learning"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "^1.26.1"
matplotlib = "^3.8.1"
torch = "^2.1.0"
torchrl = "^0.2.1"
tqdm = "^4.66.1"
gymnasium = {extras = ["mujoco"], version = "^0.29.1"}
flappy-bird-gymnasium = "^0.3.0"
hydra-core = "^1.3.2"
stable-baselines3 = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
