[tool.poetry]
name = "prt-rl"
version = "0.1.0"
description = ""
authors = ["Gavin Strunk <gavin.strunk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
torch = "^2.4.1"
mlflow = "^2.19.0"
tensordict = "^0.6.2"
tqdm = "^4.67.1"
pynput = "^1.7.7"
sphinx = "^8.1.3"
toml = "^0.10.2"
myst-parser = "^4.0.0"
sphinx-book-theme = "^1.1.3"
gymnasium = {extras = ["all"], version = "^1.0.0"}

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
