[tool.poetry]
name = "prt-rl"
version = "0.1.0"
description = ""
authors = ["Gavin Strunk <gavin.strunk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
torch = "^2.4.1"
mlflow = "^2.19.0"
tensordict = "^0.6.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
