output_file: "models/mountain_car_ppo.zip"
environment: "MountainCarContinuous-v0"
ppo:
  device: 'cuda:0'
  policy:
    num_cells: 64
    depth: 2
  value:
    num_cells: 64
    depth: 2
  collector:
    frame_skip: 1
    frames_per_batch: 8
    total_frames: 20_000
  loss:
    gamma: 0.9999
    gae_lambda: 0.9
    clip_epsilon: 0.1
    loss_critic_type: 'smooth_l1'
    entropy_eps: 0.00429
    critic_coef: 1.0
    normalize_advantage: true
    max_grad_norm: 5.0
    mini_batch_size: 256
    epochs: 10
  optim:
    lr: 7.77e-05